"""add gene and metal mapping

Revision ID: c2a7611cfffa
Revises: bc30dff642bd
Create Date: 2026-08-10 06:47:09.377134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a7611cfffa'
down_revision: Union[str, Sequence[str], None] = 'bc30dff642bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('gene_family_id', sa.UUID(), nullable=False),
    sa.Column('species', sa.String(length=150), nullable=False),
    sa.Column('ncbi_gene_id', sa.String(length=50), nullable=False),
    sa.Column('locus_tag', sa.String(length=100), nullable=True),
    sa.Column('chromosome', sa.String(length=20), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('strand', sa.String(length=10), nullable=True),
    sa.Column('gene_length', sa.Integer(), nullable=True),
    sa.Column('ncbi_assembly', sa.String(length=100), nullable=True),
    sa.Column('ncbi_chromosome_accession', sa.String(length=100), nullable=True),
    sa.Column('ncbi_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gene_family_id'], ['gene_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncbi_gene_id')
    )
    op.create_table('gene_metals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gene_id', sa.UUID(), nullable=False),
    sa.Column('metal_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Text(), nullable=True),
    sa.Column('evidence_source', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['metal_id'], ['heavy_metals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gene_metals')
    op.drop_table('genes')
    op.drop_table('gene_families')
    # ### end Alembic commands ###
