"""prevent duplicate gene metal mappings

Revision ID: fae9f54f32c1
Revises: c2a7611cfffa
Create Date: 2026-08-10 06:56:51.017112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae9f54f32c1'
down_revision: Union[str, Sequence[str], None] = 'c2a7611cfffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_gene_metal', 'gene_metals', ['gene_id', 'metal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gene_metal', 'gene_metals', type_='unique')
    # ### end Alembic commands ###
